"""Add game_user Association Table

Revision ID: e5e0cd062cd0
Revises: b3eee6eb8eba
Create Date: 2024-02-06 17:10:13.877601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e0cd062cd0'
down_revision = 'b3eee6eb8eba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
